@startuml 接收rpc流程

participant "来自其它节点的RPC客户端" as rc
participant "当前节点的RPC服务端" as rs
participant "KV存储" as kv

autonumber
rc --> rs: 转发请求，op, {key: value}
alt op == "set"
    rs --> kv: 新增记录，{key: value}
    kv --> rs: 返回结果，OK/overwrite
else op == "get"
    rs --> kv: 获取记录，key
    kv --> rs: 返回结果，{key: value} or None
else op == "delete"
    rs --> kv: 删除记录，key
    kv --> rs: 返回结果，1 or 0
end
rs --> rc: 返回结果，Any

@enduml